/**
 * [INPUT]: 依赖品牌 ID、统一错误边界与 OpenAPI 生成的 DTO/Zod/meta 模块
 * [OUTPUT]: 对外提供品牌 ID、错误边界及身份/设备/模型/bootstrap 的稳定 DTO 与 strict Zod API
 * [POS]: contracts 的 package facade，约束后续 Harness 业务包只消费验证后的跨 HTTP 语义
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

export {
  parseEnterpriseDeviceId,
  parseEnterpriseUserId,
  parseManagedModelId,
  parsePluginVersionId,
  parseRemoteSessionId,
} from './brands.js'
export type {
  EnterpriseDeviceId,
  EnterpriseUserId,
  ManagedModelId,
  PluginVersionId,
  RemoteSessionId,
} from './brands.js'
export {
  decodeEnterpriseError,
  enterpriseErrorHttpStatus,
} from './errors.js'
export type {
  EnterpriseError,
  EnterpriseErrorCode,
  EnterpriseErrorHttpStatus,
} from './errors.js'
export {
  enterpriseErrorStatuses,
  enterpriseProtocolSha256,
} from './generated/enterprise-meta.gen.js'
export type {
  AuthSourcesResponse,
  BootstrapModel,
  BootstrapResponse,
  BootstrapSnapshot,
  CursorPage,
  DeletedResourceResponse,
  Device,
  DeviceEnrollRequest,
  DeviceHeartbeatRequest,
  DeviceListResponse,
  DeviceResponse,
  DeviceStatus,
  GroupMapping,
  GroupMappingCreateRequest,
  GroupMappingListResponse,
  GroupMappingResponse,
  GrantSubjectType,
  IdentitySource,
  IdentitySourceConnection,
  IdentitySourceCreateRequestWritable,
  IdentitySourceListResponse,
  IdentitySourceResponse,
  IdentitySourceTestResponse,
  IdentitySourceUpdateRequestWritable,
  IdentitySourceStatus,
  IdentitySourceType,
  LdapSettings,
  ManagedModel,
  ManagedModelListResponse,
  ManagedModelResponse,
  ManagedModelWriteRequest,
  ModelGrant,
  ModelGrantBatchRequest,
  ModelGrantBatchResponse,
  ModelGrantListResponse,
  ModelGrantResponse,
  ModelGrantWriteRequest,
  ModelStatus,
  OidcClaimMapping,
  OidcSettings,
  LogoutResponse,
  PasswordLoginRequestWritable,
  PlatformClient,
  ProtocolMetadata,
  ProtocolPageData,
  ProtocolPageResponse,
  ProtocolSuccessResponse,
  Provider,
  ProviderCreateRequestWritable,
  ProviderListResponse,
  ProviderProbeCategory,
  ProviderProbeRequestWritable,
  ProviderProbeResponse,
  ProviderResponse,
  ProviderType,
  ProviderUpdateRequestWritable,
  QuotaExceededDetails,
  RequestId,
  Revision,
  RevisionConflictDetails,
  TokenRequest,
  TokenResponse,
  ValidationErrorDetails,
} from './generated/types.gen.js'
export {
  zAuthSourcesResponse,
  zBootstrapModel,
  zBootstrapResponse,
  zBootstrapSnapshot,
  zCursor,
  zCursorPage,
  zDeletedResourceResponse,
  zDevice,
  zDeviceEnrollRequest,
  zDeviceHeartbeatRequest,
  zDeviceListResponse,
  zDeviceResponse,
  zDeviceStatus,
  zEnterpriseErrorCode,
  zEnterpriseErrorResponse,
  zGroupMappingCreateRequest,
  zGroupMappingListResponse,
  zGroupMappingResponse,
  zGrantSubjectType,
  zIdentitySourceCreateRequestWritable,
  zIdentitySourceListResponse,
  zIdentitySourceResponse,
  zIdentitySourceTestResponse,
  zIdentitySourceUpdateRequestWritable,
  zLogoutResponse,
  zManagedModel,
  zManagedModelListResponse,
  zManagedModelResponse,
  zManagedModelWriteRequest,
  zModelGrant,
  zModelGrantBatchRequest,
  zModelGrantBatchResponse,
  zModelGrantListResponse,
  zModelGrantResponse,
  zModelGrantWriteRequest,
  zModelStatus,
  zPageLimit,
  zProtocolPageResponse,
  zProtocolSuccessResponse,
  zProvider,
  zProviderCreateRequestWritable,
  zProviderListResponse,
  zProviderProbeCategory,
  zProviderProbeRequestWritable,
  zProviderProbeResponse,
  zProviderResponse,
  zProviderType,
  zProviderUpdateRequestWritable,
  zRequestId,
  zRevision,
  zTokenRequest,
  zTokenResponse,
} from './generated/zod.gen.js'
